<%@ Page Title="" Language="C#" MasterPageFile="~/Master.Master" AutoEventWireup="true" CodeBehind="rEvaluacion.aspx.cs" Inherits="Parcial1_JohnsielWF.Registros.rEvaluacion" %>


<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">




     

</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

   <div class="panel-body">
        <div class="form-horizontal col-md-12" role="form">
       <div class="container body-content">



            <%--Evaluacion--%>
            <div class="form-group">
                <label for="EvaluacionTextBox" class="col-md-3 control-label input-sm" style="font-size: small">EvaluacionId</label>
                <div class="col-md-1 ">
                    <asp:TextBox ID="EvaluacionTextBox" runat="server" placeholder="0" class="form-control input-sm" Style="font-size: small" TextMode="Number"></asp:TextBox>
                         <asp:Button ID="BuscarBotton" runat="server" Text="Bucar" class="btn btn-primary" OnClick="BuscarBotton_Click"   />
                </div>

                </div>    
         
              

               <div class="form-group">
                    <label for="Fecha" class="col-md-3 col-form-label">Fecha</label>
                    <div class="col-md-3">
                        <asp:TextBox ID="FechaTextBox" type="date" runat="server" Class="form-control input-sm"></asp:TextBox>
                        <asp:RequiredFieldValidator ID="RFVFecha" runat="server" MaxLength="200" ValidationGroup="Analisis" ControlToValidate="FechaTextBox" ErrorMessage="Campo obligatorio" ForeColor="Black" Display="Dynamic" SetFocusOnError="True" ToolTip="Campo obligatorio"></asp:RequiredFieldValidator>
                    </div>
                    </div>
            </div>

            <%-- Nombres--%>
            <div class="form-group">
                <label for="EstudianteTexBox" class="col-md-3 control-label input-sm" style="font-size: small" >Estudiante</label>
                <div class="col-md-6">
                    <asp:TextBox ID="EstudianteTexBox" runat="server"  onkeypress="return isLetterKey(event)" placeholder="Ej. Juan Perez" class="form-control input-sm" Style="font-size: small"></asp:TextBox>
                </div>
                <asp:RequiredFieldValidator ID="Valida" runat="server" ErrorMessage="El campo &quot;Nombres&quot; esta vacio" ControlToValidate="EstudianteTexBox" ForeColor="Red" Display="Dynamic" ToolTip="Campo Nombres es obligatorio" ValidationGroup="Guardar">*</asp:RequiredFieldValidator>
            </div>

   
            

          
                <div class="form-group ">

                    <label for="CategoriaTextBox" class="col-md-3 control-label input-sm" style="font-size: small" >Categoria</label>
                <div class="col-md-2">
                    <asp:TextBox ID="CategoriaTextBox" runat="server" class="form-control input-sm" Style="font-size: small"></asp:TextBox>
                </div>
                    </div>
              <div class="form-group ">
                 <label for="ValorTexBox" class="col-md-3 control-label input-sm" style="font-size: small" >Valor</label>
                <div class="col-md-2">
                     <asp:TextBox ID="ValorTextBox" runat="server" placeholder="0" class="form-control input-sm" Style="font-size: small" TextMode="Number"></asp:TextBox>
                 </div>
                 </div>
                <div class="form-group ">
                <label for="LogradoTexbox" class="col-md-3 control-label input-sm" style="font-size: small" >Logrado</label>
                <div class="col-md-2">
                     <asp:TextBox ID="LogradoTextBox" runat="server" placeholder="0" class="form-control input-sm" Style="font-size: small" TextMode="Number"></asp:TextBox>
                </div>


             

                 </div>



                 <div class="form-group ">
                <label for="PromedioTexbox" class="col-md-3 control-label input-sm" style="font-size: small" >Promedio</label>
                <div class="col-md-2">
                    <asp:TextBox ID="PromedioTextBox" runat="server"  placeholder="0"  class="form-control input-sm" Style="font-size: small"></asp:TextBox>
                </div>


             

                 </div>

             <div class="form-group">
                
                
                         <asp:Button ID="AgregarButton" runat="server" Text="Agregar" class="btn btn-primary" OnClick="AgregarButton_Click"   />
                </div>
      
           
          <%-- Grid--%>
             <asp:GridView ID="DetalleGridView" class="col-md-3 col-md-offset-3" runat="server" AllowPaging="true" PageSize="10" ShowHeaderWhenEmpty="false" AutoGenerateDeleteButton="true" CellPadding="4" ForeColor="#333333"  GridLines="None" Width="767px" AutoGenerateColumns="true"   >
                   <Columns>
                        <asp:BoundField DataField="EvaluacionId" HeaderText="EvaluacionId" /><asp:BoundField />
                       

                    </Columns> 

                    <EmptyDataTemplate>
                        <div style="text-align: center">Se han eliminado todas las filas</div>
                    </EmptyDataTemplate>
                    <AlternatingRowStyle BackColor="White" />

                    <EditRowStyle BackColor="#2461BF" />
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EFF3FB" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#F5F7FB" />
                    <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                    <SortedDescendingCellStyle BackColor="#E9EBEF" />
                    <SortedDescendingHeaderStyle BackColor="#4870BE" />

                </asp:GridView>
              <%--Botones--%>
            <div class="panel">
                <div class="text-center">
                    <div class="form-group">
                        <asp:Button ID="NuevoButton" runat="server" Text="Nuevo" class="btn btn-primary" OnClick="NuevoButton_Click"   />
                        <asp:Button ID="GuardarButton" runat="server" Text="Guardar" class="btn btn-success" ValidationGroup="Guardar" OnClick="GuardarButton_Click"  />
                        <asp:Button ID="EliminarButton" runat="server" Text="Eliminar" class="btn btn-danger" OnClick="EliminarButton_Click" />
                    </div>
                </div>
            </div>
      </div>
       </div>
      </div>        
</asp:Content>